### ISSUE TITLE
jsp support not configured

### ISSUE THREAD

**Issue by andreagosto** [jetty-project/i-jetty#126]
What's the problem? i can't use jsp?

**Comment by janbartel** [comment]
@andreagosto wow. You're going to have to provide a lot more information for me to be able to make any comment on this at all.  In fact, it sounds like a question that you should post to the jetty user mailing list instead: jetty-users@eclipse.org.

**Comment by eborgbjerg** [comment]
On Android 4.4.2 with i-jetty 3.1 I install a rudimentary web application basically with only a 'hello'-like JSP page. The result is  HTTP ERROR 500   Problem accessing /<context>/index.jsp. Reason:
JSP support not configured.

I wonder if it is possible to compile my JSP-page to servlet instead. 
Any version of Jetty jsp-to-servlet compiler that can match i-jetty ?

**Comment by eborgbjerg** [comment]
I see that current version 3.1 of i-jetty uses Jetty 7.5.
It seems that newer versions of Jetty enables JSP support by default.
Do you plan to release i-jetty with newer version of Jetty ?

**Comment by janbartel** [comment]
You cannot do on-the-fly compilation on android as there is no runtime compiler. You must precompile any jsps you wish to use.

**Comment by surveshoeb** [comment]
I'm totally from the android background don't know much about JSP. How can I precompile any JSP's which I want to use?

**Comment by janbartel** [comment]
@surveshoeb you can use some ant targets from tomcat, or maybe the jetty jspc maven plugin depending on how you do your builds.
